### ISSUE TITLE
Different hash on different OS

### ISSUE THREAD

**Issue by TRANTANKHOA** [marc136/node-folder-hash#97] opened 2021-05-06 06:53 UTC
Hi, is there option/algo for making the hash same across e.g. Windows vs. Linux? Thanks!

**Comment by marc136** [comment] 2021-05-09 16:03
Actually the hashes should be the same.
For that I added sorting of the file names before the hash is combined. There was a bug in v4.0.0 which was fixed with 4.0.1.

Can you provide more information and also which version of folder-hash you use? 

E.g. the full output (including the children values) of a test directory that has different values on different OSes?

**Comment by TRANTANKHOA** [comment] 2021-05-10 01:08
Ah I see, I'm using v4.0.0. Let me upgrade first and I can get back to you on this. Thanks Marc!

**Comment by marc136** [comment] 2021-05-24 09:30
Hello @TRANTANKHOA did you have time to check the v4.0.1 patch?

**Comment by marc136** [comment] 2021-06-08 15:27
I'm closing this issue now, feel free to reopen it again if the bug was not fixed with v4.0.1 @TRANTANKHOA

**Closed by marc136** 2021-06-08 15:27 UTC

**Comment by Yakimych** [comment] 2021-07-16 11:27
@marc136 Unfortunately I am getting the same issue with 4.0.1 - hashing the same folder on windows produces a different hash compared to when running inside a node:14.16.1-buster container.

**Comment by marc136** [comment] 2021-07-20 11:09
That's bad @Yakimych.

Can you check in the full output (that includes the children elements by executing `hash.toString()` after creating the hash) where the difference is introduced?

Or even better, create a minimal example and upload it here as an archive?

**Comment by Yakimych** [comment] 2021-08-14 12:39
@marc136 I apologize, I went on vacation and completely missed this. I've tried to create a repro, but it looks like I was wrong - simply running the same code inside a docker container produces the same result. I suspect the issue is WSL - will investigate this further.

**Comment by Yakimych** [comment] 2021-08-14 13:11
I've performed some tests, and it looks like the discrepancy between Windows and WSL appears only if I have a linebreak in the file. Upon further examination, the reason seems to be inconsistent windows vs linux line endings when editing in VSCode. Windows produces `610a`, while WSL produces `610d 0a`. Creating the same file with vim produces the same results on both systems.

Looks like this problem does not have anything to do with hashing itself, sorry for the confusion and thanks for your help!
