### ISSUE TITLE
Bug while Hashing folders

### ISSUE THREAD

**Issue by Qurtison** [marc136/node-folder-hash#11] opened 2018-09-21 01:15 UTC
I could not figure out why the hashes on the files weren't correct. But I have identified a potential bug. 

Using the follow options 

`const options = {
    algo: 'md5',
    encoding: 'hex', 
    files: {
        include: ['*.dat'],
        ignoreRootName: true
    }  
};`

the hash of the files calculated with the name included.

I found the issue to be this line

`if (isRootElement && options.files.ignoreRootName)`

Switching it to an or statement fixes the issue and does not interfere with the hash on the folder.

`if (isRootElement || options.files.ignoreRootName)`

Sorry if this is unclear, I am terrible at explaining things

**Comment by marc136** [comment] 2018-10-11 18:06
Sorry it took me so long to respond to this @Qurtison, I was on vacation.
I will look into it this weekend

**Comment by marc136** [comment] 2018-10-21 09:07
Hello @Qurtison, I'v been trying to reproduce your issue and am not sure if I understand it correctly.

Could you create a code example that shows what you would expect as results?

In general I would expect your proposed change to alter the behavior in a way I don't want: 
The root name should only be omitted from the hash if configured with `options.files.ignoreRootName` your change would omit it always.

```
process.env.DEBUG = 'fhash:*'

const { Volume } = require('memfs'),
  path = require('path'),
  print = obj => console.log(require('util').inspect(obj, false, null))

const folderHash = require('../index'),
  prep = volume => folderHash.prep(volume, Promise)

function example1 () {
  const dir = 'folder', basename = 'file1'
  const json = {
    'abc.dat': '123',
    'abc/abc.dat': '123'
  }
  const hashElement = prep(Volume.fromJSON(json))

  const options = {
    algo: 'md5',
    encoding: 'hex',
    files: {
      include: ['*.dat'],
      ignoreRootName: true
    }
  }

  return hashElement('.', options)
    .then(result => {
      print(result)
      // hashes of /abc.dat and abc/abc.dat should be equal
      sameHash(result.children[0], result.children[1].children[0])
      
      return result
    })
}

function sameHash(a, b) {
  if (a.hash === b.hash) {
    console.log(`✓ - a.hash (${a.name}) === b.hash ({b.name})) === ${a.hash}`)
    return true
  } else {
    console.error(`✗ - hash(${a.name}) ${a.hash} should equal hash(${b.name}) ${b.hash}`)
    return false
  }
}

example1()
```

Thank you,
marc

**Comment by marc136** [comment] 2018-12-22 09:13
Hello @Qurtison, I will close this issue because I could not reproduce it and received no further information

**Closed by marc136** 2018-12-22 09:13 UTC
